### ISSUE TITLE
gotoIf -command is unstable

### ISSUE THREAD

**Issue by zaukkoo** [davehunt/selenium-ide-flowcontrol#3]
When I write a command
gotoIf | '${variable1}' == "thistext" | label1

It works. But if I save the test case, close the Selenium IDE, open it the next day - it doesn't work anymore. Throws an error "Syntax error: unterminated string literal".

**Comment by sqatomizer** [comment]
Hi,
I'm focussing the same error. But what to do with the sideflow.js file? Isn't it neccessary to build a new .xpi file?
Thanks,

**Comment by paulbors** [comment]
See Issue #5 for the problems of running this script over Selenium RC.

I ported over a different version of the same script to work with Selenium RC for integration with Maven Selenium Plugin so that our Maven CI build can run those tests.

**Comment by paulbors** [comment]
For those of you out there wondering what the difference is between Selenium IDE and Selenium RC...

The API is different and different sets of objects must be used from the way the collection of custom commands are parsed to the way the number or rows are computed for the while loop and etc.

For the IDE one needs to use the existing testCase.commands as build by the constructor on line 29 of:
https://github.com/SeleniumHQ/selenium/blob/master/ide/main/src/content/suiteTreeView.js

For the RC on the other hand, one has to use the HtmlTestFrame as constructed on line 233 by HtmlTestRunner.startTest() method via the call to testFrame.getCurrentTestCase() in the core's:
https://github.com/SeleniumHQ/selenium/blob/master/javascript/selenium-core/scripts/selenium-testrunner.js

The two sets of APIs are different. The IDE is using its own project specific ones since it allows editing those commands, whereas the core is using the ones defined in the HTML test suit. Maybe someone can research how to use the core API inside the IDE so the code doesn't have to be branched inside the if-else logic depending on what run time environment the script is running in?

For example see my port for Selenium RC of a different fork and notice the use of utils.isIDE() at:
https://github.com/paulbors/sideflow/blob/master/sideflow.js

**Comment by davehunt** [comment]
I'm no longer maintaining this add-on. Anyone is welcome to fork and continue to work on it.
